version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: laravel_app
  #   restart: always
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./:/var/www:rw
  #     - ./docker/php/conf.d:/usr/local/etc/php/conf.d
  #   environment:
  #     - APP_ENV=local
  #     - APP_DEBUG=true
  #     - APP_KEY=
  #     - DB_HOST=127.0.0.1
  #     - DB_PORT=3306
  #     - DB_DATABASE=basquete_api
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=root
  #   depends_on:
  #     - db
  #   # networks:
  #   #   - app-network
  #   command: sh -c "php artisan serve --host=0.0.0.0 --port=80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: calendario_eventos
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    # networks:
    #   - app-network

volumes:
  dbdata:

# networks:
#   app-network:
#     driver: bridge
